### ISSUE TITLE
Not able to find problematic questionnaire, polyCat, consent & feedback_bar nodes

### ISSUE THREAD

**Issue by Adn93** [campsych/concerto-platform#258] opened 2019-09-25 12:18 UTC
We are using the below Concerto version 
### Concerto Platform version - v5.0.1

We are looking to develop a test which has Strongly Disagree, Disagree, Strongly Agree, Agree type of options. Please find the screenshot link below
 
![Screen Shot 2019-09-25 at 5 47 35 PM](https://user-images.githubusercontent.com/55793325/65599956-aa913700-dfbc-11e9-8914-55a5780c4f19.png)

Please guide me with this

**Comment by cguilherme00** [comment] 2020-02-18 13:15
I have the same issue

**Comment by cguilherme00** [comment] 2020-02-19 17:11
> 
> 
> I have the same issue

Just read that they removed the questionnaire node from starter package.

**Comment by przemyslawlis** [comment] 2020-03-04 13:27
Duplicate of #272

**Closed by przemyslawlis** 2020-03-04 13:27 UTC
