### ISSUE TITLE
responsive design for run test?

### ISSUE THREAD

**Issue by johnfelipe** [campsych/concerto-platform#20] opened 2016-07-20 21:39 UTC

**Comment by przemyslawlis** [comment] 2016-07-21 12:36
Can you please be more specific what the issue is about?
Have you encountered any problems with default_layout template display on some screens?

**Comment by johnfelipe** [comment] 2016-07-25 05:24
when i run test havent responsive design?

**Comment by przemyslawlis** [comment] 2016-07-26 15:17
I might look into default_template CSS and add some device specific rules. Is there anything in particular that you think needs immediate attention?

**Comment by johnfelipe** [comment] 2016-07-28 03:43
only will be great responsivator test page

**Comment by przemyslawlis** [comment] 2016-07-28 18:06
On TODO. Closing.

**Closed by przemyslawlis** 2016-07-28 18:06 UTC
Labels: question
