### ISSUE TITLE
HTML template freezes

### ISSUE THREAD

**Issue by MariaChZ** [campsych/concerto-platform#128] opened 2017-06-14 10:25 UTC
Have anyone encountered a problem with freezing HTML while trying to edit the template? I cannot edit anything or create a new template - the moment I try to edit it, whole Concerto freezes and the only solution is to close the tab. The same happens in Concerto v4 and in v5. I have tried different browsers and computers and that happenes each time.

Edit: Probably the problem does not appear in the Mozilla Firefox.

**Comment by przemyslawlis** [comment] 2017-06-14 16:11
On what operating system and browser did you had the problem?
What version of the Concerto Platform do you use?

**Comment by MariaChZ** [comment] 2017-06-14 16:12
Windows 10: Chrome and Opera 45.0. With Firefox everything works well.

**Comment by przemyslawlis** [comment] 2018-05-30 16:59
If problem occurs in both then this is something either client related or CKEditor related. 
Can you please try the latest version ([docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide)) and confirm if you still have the same problem?

**Comment by przemyslawlis** [comment] 2018-05-30 17:13
I'm going to close this issue report for now, as there were a lot of updates since it was reported and it's possible that the issue is no longer there. 
Feel free to open new issue if you still have this problem on latest version.

**Closed by przemyslawlis** 2018-05-30 17:13 UTC
