### ISSUE TITLE
Error in docker-compose

### ISSUE THREAD

**Issue by mrmevlut** [campsych/concerto-platform#296] opened 2020-08-02 21:53 UTC
Hello

While installing the Concerto platform, I encounter an error like this

database is up-to-date
Starting concerto ...
Starting concerto ... error

ERROR: for concerto Cannot start service concerto: driver failed programming external connectivity on endpoint concerto (b235a7e98a7f6bb7fc996c34dc61116b3f4dd7b54c4903303117f408913dc87d): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in

ERROR: for concerto Cannot start service concerto: driver failed programming external connectivity on endpoint concerto (b235a7e98a7f6bb7fc996c34dc61116b3f4dd7b54c4903303117f408913dc87d): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in

ERROR: Encountered errors while bringing up the project.

I'm waiting for your help

**Comment by bkielczewski** [comment] 2020-08-03 11:15
Hi,

It's exactly what it says: listen tcp 0.0.0.0:80: bind: address already in

Meaning on this system you have something listening on port 80 already. You could change host-to-container port mapping in `docker-compose.yml`, for example:

    ports:
      - "8080:80"

This will make Concerto available on http://localhost:8080/. Other option is to stop whatever is taking up port 80 for you, probably a web server.

Closing as not a bug.

**Closed by bkielczewski** 2020-08-03 11:15 UTC

**Comment by mrmevlut** [comment] 2020-08-03 13:22
Okay! It is work.

Creating network "docker-compose_default" with the default driver
Creating database ... done
Creating concerto ... done

but <IP address>: 8080 did not work. "This page is unavailable"
