### ISSUE TITLE
Long time for install installing ggplot2 R package 

### ISSUE THREAD

**Issue by Dukhayel** [campsych/concerto-platform#154] opened 2017-10-09 06:28 UTC
I try to install, but when installing ggplot2 R package, I'm waiting for a long time and never finish.
please look my picture to see stuck install.

It is the exact issue as this user reports 
https://github.com/campsych/concerto-platform/issues/150

**Comment by Dukhayel** [comment] 2017-10-09 06:29
https://github.com/campsych/concerto-platform/issues/150

**Comment by przemyslawlis** [comment] 2017-10-30 08:16
Duplicate of #150

**Closed by przemyslawlis** 2017-10-30 08:16 UTC
