### ISSUE TITLE
Deployment failed. Write permission denied to /data folder, access to read from local mysql service denied.

### ISSUE THREAD

**Issue by kingstarr** [campsych/concerto-platform#227] opened 2019-05-27 15:25 UTC

**Comment by cvelozo** [comment] 2019-05-27 18:50
What version of concerto-platform are you using?

**Comment by kingstarr** [comment] 2019-05-28 08:33
Thank you,

I am running concerto platform version 5 dockerised.

Thank you once again,

Kingsley A. Ifedayo
Senior Software Developer
Global Performance Index International Ltd
Block 105, Plot 8, Baderinwa Alabi (Ile Ibunkun),
Lekki Phase 1, Lagos
Tel:+234-803-364-3143, +234-815-366-2867
[cid:image001.png@01D43644.F4D23580]

The information in this e-mail is confidential and is legally privileged. It is intended solely for the addressee. If this email is not intended for you, you cannot copy, distribute, or disclose its content to anyone. In the event that you are not the intended recipient please delete this mail. The content of this mail represents the opinion of the recipient and not necessarily that of Global Performance Index International Ltd. Hence Global Performance Index International Ltd., shall not accept liability for any misrepresentation in respect of this mail.

________________________________

**Comment by bkielczewski** [comment] 2019-05-28 11:09
What steps are you taking? Are you following https://github.com/campsych/concerto-platform/wiki/quickstart-guide or doing it by yourself? What operating system? Is that `/data` or `./data?`

That seems like filesystem permission problem to me.

**Comment by kingstarr** [comment] 2019-05-28 11:26
Thank you,

I am following instructions from here:
https://github.com/campsych/concerto-platform/wiki/deployment-guide.

Using the following directives:
docker run -v data:/data -e DB_HOST="localhost" -e DB_PASSWORD="mygpiadminpassword" -p 8080:80 campsych/concerto-platform, to pull and run the container.

My server is running CentOS Linux release 7.6.1810 and I am running installation using root account.

Thank you again,

Kingsley A. Ifedayo
Senior Software Developer
Global Performance Index International Ltd
Block 105, Plot 8, Baderinwa Alabi (Ile Ibunkun),
Lekki Phase 1, Lagos
Tel:+234-803-364-3143, +234-815-366-2867
[cid:image001.png@01D43644.F4D23580]

The information in this e-mail is confidential and is legally privileged. It is intended solely for the addressee. If this email is not intended for you, you cannot copy, distribute, or disclose its content to anyone. In the event that you are not the intended recipient please delete this mail. The content of this mail represents the opinion of the recipient and not necessarily that of Global Performance Index International Ltd. Hence Global Performance Index International Ltd., shall not accept liability for any misrepresentation in respect of this mail.

**Comment by bkielczewski** [comment] 2019-05-28 12:53
Ok. Can't reproduce but:
- change `-v data:/data` to absolute path where you know you have write access
- if your database is running on localhost then run docker with `--network=host`. Otherwise for the container localhost resolves to the container, not the host system. Port 80 needs to be free on the host system, because port mappings like 8080:80 are ignored in host network mode.

So this will be something like:

`
docker run -v /path/to/data:/data -e DB_HOST="somehost" -e DB_PASSWORD="somepassword" -p 8080:80 campsych/concerto-platform
`

**Comment by bkielczewski** [comment] 2019-05-30 11:20
In the latest build we also have support for `NGINX_PORT` env variable for scenarios where port mapping is impossible (i.e. running with `--network=host`). 

Closing, feel free to reopen if you still have a problem.

**Closed by bkielczewski** 2019-05-30 11:20 UTC

**Comment by kingstarr** [comment] 2019-05-31 07:48
Thank you very much for your time and efforts,

Kindly find attached a screenshot from my server showing concerto installation error.

This indicates that there is a permission issue inside of the container.

Kindly clarify.

With Compliments,

Kingsley A. Ifedayo
Senior Software Developer
Global Performance Index International Ltd
Block 105, Plot 8, Baderinwa Alabi (Ile Ibunkun),
Lekki Phase 1, Lagos
Tel:+234-803-364-3143, +234-815-366-2867
[cid:image001.png@01D43644.F4D23580]

The information in this e-mail is confidential and is legally privileged. It is intended solely for the addressee. If this email is not intended for you, you cannot copy, distribute, or disclose its content to anyone. In the event that you are not the intended recipient please delete this mail. The content of this mail represents the opinion of the recipient and not necessarily that of Global Performance Index International Ltd. Hence Global Performance Index International Ltd., shall not accept liability for any misrepresentation in respect of this mail.

________________________________
