### ISSUE TITLE
Windows 10 installation issue

### ISSUE THREAD

**Issue by gambitwi** [campsych/concerto-platform#157] opened 2017-10-25 19:47 UTC
The installer hangs trying to install the ggplot2 R package

**Comment by jkrow** [comment] 2017-10-25 19:56
Determined issue. Had to find true installer from .appref-ms file. Ran true installer as adminstrator and installation completed successfully

**Comment by przemyslawlis** [comment] 2017-10-30 08:05
It can take several minutes (over half hour in some cases) to complete ggplot2 installation. Closing for now. Feel free to reopen if you still can't progress past it.

**Closed by przemyslawlis** 2017-10-30 08:05 UTC

**Comment by przemyslawlis** [comment] 2017-10-30 08:16
Duplicate of #150
