### ISSUE TITLE
SQL error when using Start_Session Node

### ISSUE THREAD

**Issue by mikeliddle** [campsych/concerto-platform#142] opened 2017-07-14 14:28 UTC
I'm pretty new to Concerto, but I have it running on a local ubuntu server and I've read through basically all the documentation to try to figure this out, but I'm trying to use the start_session node to create a login screen for people to authenticate with before taking the test.  However, upon registering an error occurs and the execution halts.
The following is shown in my browser's console:
![screen shot 2017-07-14 at 8 20 16 am](https://user-images.githubusercontent.com/7586950/28216041-54c8e8f4-686d-11e7-967c-69b9733be865.png)
since none of this information is actually sensitive, here's the request body that is being sent to the server as well:
![screen shot 2017-07-14 at 8 22 28 am](https://user-images.githubusercontent.com/7586950/28216118-aa156f4e-686d-11e7-9a5b-5d3bd839c9ff.png)

I am using a custom table which is described as such:
![screen shot 2017-07-14 at 8 45 50 am](https://user-images.githubusercontent.com/7586950/28217007-dea3c988-6870-11e7-90aa-089b83bace62.png)

And here's how it appears in Concerto:
![screen shot 2017-07-14 at 8 25 45 am](https://user-images.githubusercontent.com/7586950/28216225-12eb432c-686e-11e7-80b7-c2b964fd0d77.png)

I am currently getting a 500 error when I try to add a row to this table when the client Posts to the collection endpoint, so this might be related however, I didn't see any useful information in either the request or response body of that request.  Any ideas what is causing this?

**Comment by przemyslawlis** [comment] 2017-08-01 17:36
> I am currently getting a 500 error when I try to add a row to this table when the client Posts to the collection endpoint

^ I see that you must have edited the id field of table created in Concerto manually and changed its name to uid. This one field should not be changed as there is a lot of logic that depends on primary key field to be named **id** in each tables that should be accessible from Concerto administration panel.

> I'm trying to use the start_session node to create a login screen for people to authenticate with before taking the test. However, upon registering an error occurs and the execution halts.

^ Is it possible for you to send me test export so I can recreate it locally?

**Comment by mikeliddle** [comment] 2017-08-07 17:11
[Test_session_test.concerto.zip](https://github.com/campsych/concerto-platform/files/1205556/Test_session_test.concerto.zip)

**Comment by przemyslawlis** [comment] 2018-05-30 17:10
There has been quite few updates to **start_session_node** in the past. 
Can you check the latest version ([docker-compose Installation guide](https://github.com/campsych/concerto-platform/wiki/docker-compose-Installation-guide)) and see if the problem still exist for you? 
Closing for now. Feel free to open new issue if the problem is still there.

**Closed by przemyslawlis** 2018-05-30 17:10 UTC
