### ISSUE TITLE
Textbox functionality when running CAT questions

### ISSUE THREAD

**Issue by roseKQ** [campsych/concerto-platform#109] opened 2017-03-28 11:52 UTC
Hello,

I have been trying to create a question that can be answered by textbox instead of radio buttons as per the instructions on the CAT item bank definition. 

"Item bank

CAT item bank definition.

Leave item response options list empty for open question."

I have tried this but it runs an error in the console and stops the test - here is the error message - 

**<simpleError in concerto.template.join(templateId = CAT_template, params = list(paragraph = paragraph,     question = question$question, response_type = response_type,     response_options = toJSON(options), section_classes = section_classes,     section_styles = section_styles)): object 'section_classes' not found>
[1] "responding to server..."
[1] "responded to server"
[1] "updating session..."
Error in value[[3L]](cond) : Error executing test logic.
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning messages:
1: Closing open result sets 
2: Closing open result sets 
3: Closing open result sets 
4: Closing open result sets 
Execution halted**

Please let me know what's happening and what I'm doing wrong, thank you

**Comment by przemyslawlis** [comment] 2017-03-29 12:12
This is most probably a duplicate of #94.
Please check the issue report above for a temporary solution for it until the fix will make it to the public repository.

**Closed by przemyslawlis** 2017-03-29 12:12 UTC
