### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by oloabbott** [campsych/concerto-platform#143] opened 2017-07-14 19:33 UTC
I have succeeded in installing concerto launcher on windows, but when I clicked on run, the browser displayed the image below

![image_1](https://user-images.githubusercontent.com/30015105/28247719-115203e2-69eb-11e7-8b40-e9903426b38f.png)

**Comment by jkrow** [comment] 2017-10-25 20:11
I am getting the same error on windows 10 64 bit

**Comment by przemyslawlis** [comment] 2017-10-30 09:08
Duplicate of #144

**Closed by przemyslawlis** 2017-10-30 09:08 UTC
